# Generated by Django 3.1.5 on 2021-04-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_validate',
            field=models.BooleanField(default=False),
        ),
    ]
